type: "SigNNOneHand"

input_stream: "LANDMARKS:landmarks"
output_stream: "RENDER_DATA:output"

node {
  calculator: "OneHandGateCalculator"
  input_stream: "LANDMARKS:landmarks"
  output_stream: "LANDMARKS:hand_gated"
  output_stream: "SIGNAL:no_hands"
    node_options: {
      [type.googleapis.com/mediapipe.HandGateCalculatorOptions] {
        memory_in_seconds: 1
        percent_of_one_hand_required: .65
      }
    }
}

node {
    calculator: "StringEmitterCalculator"
    input_stream: "SIGNAL:no_hands"
    output_stream: "STRING:invalid_hands_text"
    node_options: {
      [type.googleapis.com/mediapipe.StringEmitterCalculatorOptions] {
        given_string: "Display 1 hand"
      }
    }
}

node {
  calculator: "StringToRenderDataCalculator"
  input_stream: "STRING:invalid_hands_text"
  output_stream: "RENDER_DATA:invalid_hands_render"
}


node {
  calculator: "FPSCalculatorOneHand"
  input_stream: "LANDMARKS:hand_gated"
  output_stream: "DOUBLE:fps"
}

node {
  calculator: "FPSGateCalculator"
  input_stream: "DOUBLE:fps"
  input_stream: "LANDMARKS:hand_gated"
  output_stream: "LANDMARKS:fps_gated"
  output_stream: "SIGNAL:invalid_fps"
  output_stream: "DOUBLE:fps_gated_fps"
  node_options: {
    [type.googleapis.com/mediapipe.FpsGateCalculatorOptions] {
        memory_in_seconds: 5
        minimum_fps: 3
      }
  }
}

node {
  calculator: "LandmarkHistoryCalculator"
  input_stream: "LANDMARKS:fps_gated"
  output_stream: "LANDMARKS_HISTORY:landmarks_history"
  node_options: {
    [type.googleapis.com/mediapipe.LandmarkHistoryCalculatorOptions] {
      memory_in_seconds: 2
      }
  }
}

node {
  calculator: "StringEmitterCalculator"
  input_stream: "SIGNAL:invalid_fps"
  output_stream: "STRING:invalid_fps_text"
  node_options: {
    [type.googleapis.com/mediapipe.StringEmitterCalculatorOptions] {
      given_string: "FPS too low"
      }
  }
}

node {
  calculator: "StringToRenderDataCalculator"
  input_stream: "STRING:invalid_fps_text"
  output_stream: "RENDER_DATA:invalid_fps_render"
}

node {
  calculator: "PointVelocityCalculatorOneHand"
  input_stream: "LANDMARKS:fps_gated"
  input_stream: "DOUBLE:fps_gated_fps"
  output_stream: "DOUBLE:velocity"
}

node{
  calculator: "StaticDynamicGateCalculator"
  input_stream: "LANDMARKS:fps_gated"
  input_stream: "LANDMARKS_HISTORY:landmarks_history"
  input_stream: "DOUBLE:velocity"
  output_stream: "LANDMARKS:static_landmarks"
  output_stream: "LANDMARKS_HISTORY:dynamic_landmarks"
  node_options: {
    [type.googleapis.com/mediapipe.StaticDynamicGateOptions] {
      dynamic_threshold: .095
      maximum_extra_dynamic_frames: 8
      velocity_history: 1
    }
  }
}

node {
  calculator: "SigNNDynamic"
  input_stream: "LANDMARKS_HISTORY:dynamic_landmarks"
  output_stream: "RENDER_DATA:dynamic_render"
}

node {
  calculator: "SigNNStatic"
  input_stream: "LANDMARKS:static_landmarks"
  output_stream: "RENDER_DATA:static_render"
}

node {
  calculator: "SignnEndGateCalculator"
  input_stream: "static_render"
  input_stream: "dynamic_render"
  input_stream: "invalid_fps_render"
  input_stream: "invalid_hands_render"
  output_stream: "RENDER_DATA:output"
  input_stream_handler {
    input_stream_handler: 'ImmediateInputStreamHandler'
  }
}